#!/bin/bash
#-> source me in bashrc
# setting requried for MPV (before quit-watch-later command is used in mpv, which is bound to Q by default)
# for this script to work as intended: write-filename-in-watch-later-config=yes
# todo: check if 'write-filename-in-watch-later-config=yes' setting set

# adds all subtitle types from media files folder and cwd
alias mpv='command mpv --sub-auto=all --sub-file-paths=".:${PWD}"'

# opens MPVs and queues last saved source from MPV into MPVs playlist
queue-MPVWatchLater(){
	mpv "$(sed /"redirect entry"/d ~/.config/mpv/watch_later/$(/usr/bin/ls -t ~/.config/mpv/watch_later/ | head -1) | head -1 | sed 's/# //')"
}

# lists saved sources from MPV
print-MPVWatchLaterList () {
	ls -t ~/.config/mpv/watch_later/ \
	| while read -r entry
		do sed /"redirect entry"/d ~/.config/mpv/watch_later/"$entry" \
		| head -1
	done | \grep ^\# | sed "s/# //"
}

# opens MPVs and queues saved sources from MPV into MPVs playlist
queue-MPVWatchLaterList(){
	readarray playlist < <(print-MPVWatchLaterList) && mpv "${playlist[@]}"
}
