#!/bin/bash
#to source
call () 
{ 
    nohup "$@" > /dev/null 2> /dev/null &
}
alias mpv="command mpv --sub-auto=all --sub-file-paths=\".:\${PWD}\""
#todo: queue all
queue-MPVWatchLater(){
	call mpv "$(sed /"redirect entry"/d ~/.config/mpv/watch_later/$(/usr/bin/ls -t ~/.config/mpv/watch_later/ | head -1) | head -1 | sed 's/# //')"
}

# lists saved sources from MPV
# setting requried for MPV (before quit-watch-later command is sued in mpv, which is bound to Q by default)
# for this script to work as intended: write-filename-in-watch-later-config=yes
print-MPVWatchLaterList () {
	ls -t ~/.config/mpv/watch_later/ \
	| while read -r entry
		do sed /"redirect entry"/d ~/.config/mpv/watch_later/"$entry" \
		| head -1
	done | \grep ^\# | sed "s/# //"
}
